# Generated by Django 4.1.13 on 2025-07-17 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("genre_id", models.IntegerField(unique=True)),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="MovieCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("movie_id", models.IntegerField(unique=True)),
                ("title", models.CharField(max_length=255)),
                ("overview", models.TextField()),
                (
                    "poster_path",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "backdrop_path",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("release_date", models.DateField(blank=True, null=True)),
                ("vote_average", models.FloatField()),
                ("vote_count", models.IntegerField()),
                ("runtime", models.IntegerField(blank=True, null=True)),
                ("genres", models.JSONField(default=list)),
                ("production_companies", models.JSONField(default=list)),
                ("production_countries", models.JSONField(default=list)),
                ("spoken_languages", models.JSONField(default=list)),
                ("adult", models.BooleanField(default=False)),
                ("popularity", models.FloatField()),
                ("cached_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-popularity"],
            },
        ),
    ]
