# Generated by Django 4.1.13 on 2025-07-17 06:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion



class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WatchlistItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("movie_id", models.IntegerField()),
                ("movie_title", models.CharField(max_length=255)),
                (
                    "movie_poster",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                ("movie_overview", models.TextField(blank=True)),
                ("movie_release_date", models.DateField(blank=True, null=True)),
                ("movie_rating", models.FloatField(blank=True, null=True)),
                (
                    "watch_status",
                    models.CharField(
                        choices=[
                            ("want_to_watch", "Want to Watch"),
                            ("watched", "Watched"),
                        ],
                        default="want_to_watch",
                        max_length=20,
                    ),
                ),
                ("user_rating", models.IntegerField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("watched_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="watchlist",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "watchlist_items",
            },
        ),
        migrations.CreateModel(
            name="UserMovieInteraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("movie_id", models.IntegerField()),
                (
                    "interaction_type",
                    models.CharField(
                        choices=[
                            ("view", "Viewed"),
                            ("add_to_watchlist", "Added to Watchlist"),
                            ("remove_from_watchlist", "Removed from Watchlist"),
                            ("mark_watched", "Marked as Watched"),
                            ("mark_unwatched", "Marked as Unwatched"),
                        ],
                        max_length=30,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_movie_interactions",
            },
        ),
    ]
